# Site settings
title: Fleggo | Responsive Flexbox Grid System 
email: greg.tarnoff@me.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Fleggo/" # the subpath of your site, e.g. /blog/
url: "http://gtarnoff/github.io" # the base hostname & protocol for your site
twitter_username: gregtarnoff
github_username:  gtarnoff

# Build settings
markdown: kramdown
assets:
  # Pathname of the destination of generated (bundled) assets relative
  # to the destination of the root.
  #
  dirname: assets
  #
  # Base URL of assets paths.
  #
  baseurl: /Fleggo/assets/
  #
  # Pathnames where to find assets relative to the root of the site.
  #
  sources:
    #    - images
    - _assets/js
    - _assets/css
  #
  # Sets compressors for the specific types of file: `js`, or `css`.
  # No compression by default.
  #
  # Possible variants:
  #
  #     css  => 'yui', 'sass', nil
  #     js   => 'yui', 'uglifier', nil
  #
  #compress:
  #  js:   uglifier
  #  css:  sass
  # Sets cachebusting policy for generated assets.
  #
  # Possible variants:
  #
  #   none - disables cachebusting
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css
  #
  #   soft - leave filenames as-is, but `?cb=<md5>` suffix for URLs generated
  #          with `asset_path`, `javascript` and `stylesheet`:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app.css
  #     output URL:   /assets/javascripts/app.css?cb=4f41243847da693a4f356c0486114bc6
  #
  #   hard - (default) injects cachebusting checksum into processed filename:
  #
  #     source file:  _assets/javascripts/app.css
  #     output file:  _site/assets/javascriptis/app-4f41243847da693a4f356c0486114bc6.css
  #     output URL:   /assets/javascripts/app-4f41243847da693a4f356c0486114bc6.css
  #
  cachebust: none
  #
  # Whenever or not cache compiled assets (disabled by default).
  # See `Compilation Cache` section of README for details.
  #
  cache_assets: false
  #
  # Specifies list of MIME types that needs to have gzipped versions.
  # You can set it to `false` to disable gzipping. Only javascripts and
  # stylesheets are gzipped by default.
  #
  # gzip: [ text/css, application/javascript ]
